"use client";

import { type FormEvent, useEffect, useState } from "react";
import { CopySimpleIcon as Copy } from "@phosphor-icons/react/dist/ssr/CopySimple";
import { MagnifyingGlassIcon as Search } from "@phosphor-icons/react/dist/ssr/MagnifyingGlass";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import type { OpenGraphData } from "@/lib/tools/network";
import { ToolButton } from "@/components/tools/tool-button";
import { ToolPanel, toolInputClassName } from "@/components/tools/tool-shell";

function setUrlQuery(router: ReturnType<typeof useRouter>, pathname: string, params: ReturnType<typeof useSearchParams>, key: string, value: string) { const next = new URLSearchParams(params.toString()); next.set(key, value); router.replace(`${pathname}?${next}`, { scroll: false }); }
function display(value: unknown) { if (Array.isArray(value)) return value.join(", "); if (typeof value === "string") return value; return value ? String(value) : "—"; }

function LinkPreview({ name, data }: { name: string; data: OpenGraphData }) {
  const image = data.twitterImage?.[0] ?? data.ogImage?.[0]; const title = data.twitterTitle ?? data.ogTitle ?? data.title ?? "Untitled page"; const description = data.twitterDescription ?? data.ogDescription ?? data.description ?? "No description found."; const url = data.ogUrl ?? data.canonical ?? "";
  return <article className="overflow-hidden border border-foreground/10 bg-background"><div className="border-b border-foreground/10 px-3 py-2 text-xs lowercase text-foreground/60">{name}</div>{image ? <img src={image} alt="Open graph preview" className="aspect-[2/1] w-full object-cover" /> : <div className="aspect-[2/1] bg-card" />}<div className="space-y-1 p-3"><p className="truncate text-xs text-foreground/55">{url}</p><h3 className="line-clamp-1 font-medium">{title}</h3><p className="line-clamp-2 text-sm text-foreground/65">{description}</p></div></article>;
}

export function OpenGraphInspector() {
  const router = useRouter(); const pathname = usePathname(); const params = useSearchParams(); const [initial] = useState(() => params.get("url") ?? ""); const [url, setUrl] = useState(initial); const [data, setData] = useState<OpenGraphData | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  const inspect = async (value: string) => { const requested = /^https?:\/\//i.test(value) ? value : `https://${value}`; setLoading(true); setError(null); setData(null); try { const response = await fetch(`/api/tools/metadata?url=${encodeURIComponent(requested)}`); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Unable to inspect that URL."); setData(body.data); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to inspect that URL."); } finally { setLoading(false); } };
  useEffect(() => { if (initial) void inspect(initial); }, [initial]); // Query state is read once; user submissions own subsequent fetches.
  const submit = (event: FormEvent) => { event.preventDefault(); setUrlQuery(router, pathname, params, "url", url); void inspect(url); };
  const sections = data ? [["basic metadata", { title: data.title, description: data.description, favicon: data.favicon, canonical: data.canonical, author: data.author, robots: data.robots, viewport: data.viewport }], ["open graph", { title: data.ogTitle, description: data.ogDescription, url: data.ogUrl, type: data.ogType, siteName: data.ogSiteName, locale: data.ogLocale, images: data.ogImage }], ["twitter card", { card: data.twitterCard, site: data.twitterSite, creator: data.twitterCreator, title: data.twitterTitle, description: data.twitterDescription, images: data.twitterImage }]] : [];
  return <div className="space-y-7"><ToolPanel><form onSubmit={submit} className="flex flex-wrap gap-2"><input type="url" required value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://example.com" className={`${toolInputClassName} min-w-55 flex-1`} /><ToolButton type="submit" disabled={loading}><Search size={16} />{loading ? "inspecting…" : "inspect"}</ToolButton></form>{error && <p role="alert" className="mt-3 text-sm text-destructive">{error}</p>}</ToolPanel>{data && <><section><h2 className="mb-3 text-xl">social previews</h2><div className="grid gap-4 sm:grid-cols-2"><LinkPreview name="Discord" data={data} /><LinkPreview name="LinkedIn" data={data} /><LinkPreview name="Facebook" data={data} /><LinkPreview name="X / Twitter" data={data} /></div></section><section className="space-y-4"><h2 className="text-xl">raw metadata</h2>{sections.map(([title, content]) => <ToolPanel key={title as string}><h3 className="mb-4 text-lg">{title as string}</h3><dl className="space-y-2 text-sm">{Object.entries(content as Record<string, unknown>).filter(([, value]) => Boolean(value)).map(([key, value]) => <div key={key} className="grid gap-1 border-b border-foreground/10 pb-2 sm:grid-cols-[12rem_1fr]"><dt className="text-foreground/60">{key}</dt><dd className="break-all">{display(value)}</dd></div>)}</dl></ToolPanel>)}{data.metaTags.length > 0 && <ToolPanel><h3 className="mb-4 text-lg">additional meta tags</h3><div className="space-y-2 font-mono text-xs">{data.metaTags.map((tag, index) => <p key={`${tag.name}-${tag.property}-${index}`} className="break-all border-b border-foreground/10 pb-2">{tag.name ? `name="${tag.name}" ` : ""}{tag.property ? `property="${tag.property}" ` : ""}content=&quot;{tag.content}&quot;</p>)}</div></ToolPanel>}</section></>}</div>;
}

type WhoisResponse = { domain: string; remaining: number; resetIn: number; sections: Record<string, Record<string, unknown>> };
export function WhoisLookup() {
  const router = useRouter(); const pathname = usePathname(); const params = useSearchParams(); const [initialDomain] = useState(() => params.get("domain") ?? ""); const [domain, setDomain] = useState(initialDomain); const [result, setResult] = useState<WhoisResponse | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null);
  const lookup = async (value: string) => { setLoading(true); setError(null); try { const response = await fetch(`/api/tools/whois?domain=${encodeURIComponent(value)}`); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "WHOIS lookup failed."); setResult(body); } catch (reason) { setResult(null); setError(reason instanceof Error ? reason.message : "WHOIS lookup failed."); } finally { setLoading(false); } };
  useEffect(() => { if (initialDomain) void lookup(initialDomain); }, [initialDomain]);
  const submit = (event: FormEvent) => { event.preventDefault(); setUrlQuery(router, pathname, params, "domain", domain); void lookup(domain); };
  return <div className="space-y-6"><ToolPanel><form onSubmit={submit} className="flex flex-wrap gap-2"><input required value={domain} onChange={(event) => setDomain(event.target.value)} placeholder="example.com" className={`${toolInputClassName} min-w-55 flex-1`} /><ToolButton type="submit" disabled={loading}><Search size={16} />{loading ? "looking up…" : "lookup"}</ToolButton></form>{result && <p className="mt-3 text-xs text-foreground/60">{result.remaining} requests remaining · resets in {result.resetIn} minutes</p>}{error && <p role="alert" className="mt-3 text-sm text-destructive">{error}</p>}</ToolPanel>{result && <div className="space-y-4">{Object.entries(result.sections).map(([title, content]) => { const rows = Object.entries(content).filter(([, value]) => Boolean(value)); return rows.length ? <ToolPanel key={title}><h2 className="mb-4 text-lg capitalize">{title}</h2><dl className="space-y-2 text-sm">{rows.map(([key, value]) => <div key={key} className="grid gap-1 border-b border-foreground/10 pb-2 sm:grid-cols-[12rem_1fr]"><dt className="capitalize text-foreground/60">{key.replace(/[A-Z]/g, (letter) => ` ${letter}`)}</dt><dd>{display(value)}</dd></div>)}</dl></ToolPanel> : null; })}</div>}</div>;
}

type SubdomainResult = { domain: string; subdomains: { name: string; certificates: { id: string; loggedAt: string; notBefore: string; notAfter: string; issuer: string; includesWildcard: boolean }[] }[] };
export function SubdomainFinder() {
  const router = useRouter(); const pathname = usePathname(); const params = useSearchParams(); const [initialDomain] = useState(() => params.get("domain") ?? ""); const [domain, setDomain] = useState(initialDomain); const [result, setResult] = useState<SubdomainResult | null>(null); const [loading, setLoading] = useState(false); const [error, setError] = useState<string | null>(null); const [copied, setCopied] = useState<string | null>(null);
  const search = async (value: string) => { setLoading(true); setError(null); try { const response = await fetch(`/api/tools/subdomains?domain=${encodeURIComponent(value)}`); const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Unable to find subdomains."); setResult(body); } catch (reason) { setResult(null); setError(reason instanceof Error ? reason.message : "Unable to find subdomains."); } finally { setLoading(false); } };
  useEffect(() => { if (initialDomain) void search(initialDomain); }, [initialDomain]);
  const submit = (event: FormEvent) => { event.preventDefault(); setUrlQuery(router, pathname, params, "domain", domain); void search(domain); };
  const copy = async (name: string) => { await navigator.clipboard.writeText(name); setCopied(name); window.setTimeout(() => setCopied(null), 1800); };
  return <div className="space-y-6"><ToolPanel><form onSubmit={submit} className="flex flex-wrap gap-2"><input required value={domain} onChange={(event) => setDomain(event.target.value)} placeholder="example.com" className={`${toolInputClassName} min-w-55 flex-1`} /><ToolButton type="submit" disabled={loading}><Search size={16} />{loading ? "searching…" : "search"}</ToolButton></form>{error && <p role="alert" className="mt-3 text-sm text-destructive">{error}</p>}</ToolPanel>{result && <ToolPanel><h2 className="mb-4 text-lg">{result.subdomains.length} subdomains for {result.domain}</h2><div className="space-y-2">{result.subdomains.map((subdomain) => <details key={subdomain.name} className="border border-foreground/10"><summary className="flex cursor-pointer list-none items-center gap-3 p-3"><span className="min-w-0 flex-1 truncate font-medium">{subdomain.name}</span>{subdomain.certificates.some((certificate) => certificate.includesWildcard) && <span className="text-xs text-foreground/60">wildcard</span>}<span className="text-xs text-foreground/60">{subdomain.certificates.length} certificates</span><ToolButton variant="quiet" className="min-h-0 p-1" aria-label={`Copy ${subdomain.name}`} onClick={(event) => { event.preventDefault(); void copy(subdomain.name); }}><Copy size={15} /></ToolButton></summary><div className="border-t border-foreground/10 p-3">{copied === subdomain.name && <p className="mb-2 text-xs text-foreground/60">Copied.</p>}<div className="grid gap-3 sm:grid-cols-2">{subdomain.certificates.map((certificate) => <div key={certificate.id} className="bg-card p-3 text-sm"><p className="font-medium">{certificate.issuer}</p><p className="mt-2 text-foreground/60">valid {new Date(certificate.notBefore).toLocaleDateString()} – {new Date(certificate.notAfter).toLocaleDateString()}</p><p className="mt-1 text-foreground/60">logged {new Date(certificate.loggedAt).toLocaleDateString()}</p></div>)}</div></div></details>)}</div></ToolPanel>}</div>;
}
